openapi: '2.0'
info:
  title: Ellie Mae REST standard endpoints
  description: Standard endpoints built into all Ellie Mae RESTful services.
  contact:
    name: Ellie Mae Inc.
    url: https://elliemae.com
    email: support@elliemae.com
consumes:
- application/json
produces:
- application/json
paths:
  /diagnostics/v1/health:
    get:
      tags:
      - Health
      summary: An endpoint that obtains the health of the current service host.
      description: An endpoint that obtains the health of the current service host.
      operationId: GET_/diagnostics/v1/health
      parameters:
      - name: Dependencies
        in: query
        required: false
        description: The type of health check to be performed on dependencies.  by
          default.
        type: string
        enum:
        - None
        - Now
        - Last
      - name: X-Correlation-Id
        in: header
        required: false
        type: string
      responses:
        '200':
          description: The host health has been successfully retrieved.
          schema:
            $ref: "#/definitions/getHealthResponse"
          headers:
            X-Correlation-Id:
              type: string
        '403':
          description: The user does not have sufficient privileges to perform this
            action.
          schema:
            $ref: "#/definitions/restError"
          headers:
            X-Correlation-Id:
              type: string
        '500':
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request.
          schema:
            $ref: "#/definitions/restError"
          headers:
            X-Correlation-Id:
              type: string
        '501':
          description: The dependencies health check type Last is not supported.
          schema:
            $ref: "#/definitions/restError"
          headers:
            X-Correlation-Id:
              type: string
definitions:
  restError:
    title: RestError
    properties:
      code:
        title: code
        description: The service-specific code for this error, in the format "SERVICENAME-NUMBER",
          such as "EBS-0001". Errors generated by the REST framework do not contain
          codes. Optional.
        type: string
      details:
        title: details
        description: The detailed message describing the nature of the error. Optional.
        type: string
      errors:
        title: errors
        description: The errors that caused this error.
        type: array
        items:
          $ref: "#/definitions/restError"
          type: object
      summary:
        title: summary
        description: A brief description of the error condition intended for the end
          user. Optional.
        type: string
    description: Encapsulates the details about an error encountered in the a service
      call, in lieu of a response model.
    type: object
  getHealthResponse:
    title: GetHealthResponse
    properties:
      appDate:
        title: appDate
        description: The date and time at which the main application executable was
          created, if it can be determined.
        type: string
        format: date-time
      appName:
        title: appName
        description: The name of the service instance, as defined in the application
          configuration.
        type: string
      appUrn:
        title: appUrn
        description: The unique global identifer of the application, as defined in
          the application configuration.
        type: string
        format: uri
      appVersion:
        title: appVersion
        description: The version number of the main application executable, if it
          can be determined.
        type: string
      dependencies:
        $ref: "#/definitions/dependencyHealthMap"
        title: dependencies
        description: A table providing the health of dependencies, if requested. The
          key is the dependency name, the value is an object indicating the current
          health of the dependency. The down dependencies are always on top.
      location:
        title: location
        description: The location of the service instance, as defined in the application
          configuration.
        type: string
      machineName:
        title: machineName
        description: The name of the machine on which this host is running.
        type: string
      osVersion:
        title: osVersion
        description: The name of the operating system that the host is using.
        type: string
      publicUrl:
        title: publicUrl
        description: The public url of the service instance, as defined in the application
          configuration.
        type: string
        format: uri
      startDate:
        title: startDate
        description: The date/time at which the host started.
        type: string
        format: date-time
      status:
        title: status
        description: The health status of the service as a whole.
        type: string
        enum:
        - UP
        - DOWN
      upTime:
        title: upTime
        description: The duration of time that the host has been running.
        type: string
        pattern: "^\\s*(?:\\d{1,2})(?::\\d{1,2}){0,3}(?:\\.\\d+)?$"
    description: Response to `GetHealthRequest`.
    type: object
  dependencyHealth:
    title: DependencyHealth
    properties:
      details:
        title: details
        description: Details about the health check, such as the reason why the health
          check failed.
        type: object
      status:
        title: status
        description: The health status of this dependency.
        type: string
        enum:
        - UP
        - DOWN
      time:
        title: time
        description: The date/time at which the health check on the dependency was
          performed.
        type: string
        format: date-time
    description: Encapsulates the health of a dependency determined during health
      check.
    type: object
  dependencyHeathMap:
    additionalProperties:
      $ref: "#/definitions/dependencyHealth"
    type: object
